apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
        - name: file-watcher
          image: ghcr.io/dblencowe/k8s-reloader:latest
          args: ["/etc/nginx/nginx.conf"]
          env:
            - name: DEPLOYMENT_NAME
              value: nginx-deployment
            - name: DEPLOYMENT_NAMESPACE
              value: default

